### ISSUE TITLE
Code not present

### ISSUE THREAD

**Issue by FullBinaryAlchemist** [divsin123/firstproject#2]
@divsin123 Your code has been removed . So checkout the messageforyou file to see how to restore the code. ;)

**Comment by divsin123** [comment]
> @divsin123 Your code has been removed . So checkout the messageforyou file to see how to restore the code. ;)

**Comment by FullBinaryAlchemist** [comment]
@divsin123 The code still hasn't been restored so why was the issue closed? And the label "duplicate" has been used incorrectly.

**Comment by divsin123** [comment]
https://IncredibleBlushingTask.mahmoudrawy1.repl.run

**Comment by divsin123** [comment]
https://repl.it/languages/python3

**Comment by divsin123** [comment]
https://repl.it/live/oK1TdHucdvJLtA
